# Generated by Django 5.1.4 on 2025-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
