# Generated by Django 5.1.4 on 2025-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_cart_order_cartitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
