# Generated by Django 5.1.4 on 2025-01-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_order_city_order_country_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('blik', 'Blik'), ('paypal', 'PayPal'), ('cod', 'Za pobraniem')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('home_delivery', 'Dostawa do domu'), ('parcel_locker', 'Dostawa do paczkomatu')], max_length=50),
        ),
    ]
